spring:
#  jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
#  mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tacan?characterEncoding=utf-8
    username: root
    password: admin
#    freemarker
  freemarker:
    allowRequestOverride: false
    allowSessionOverride: false
    cache: false
    checkTemplateLocation: true
    contentType: text/html
    exposeRequestAttributes: false
    exposeSessionAttributes: false
    exposeSpringMacroHelpers: false
    suffix: .ftl
    templateLoaderPath: classpath:/templates/  #表示所有的模板文件都放在该目录下
    charset: UTF-8

  mvc:
    static-path-pattern: /static/**
mybatis:
#  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.bcfou.repository

